### ISSUE TITLE
SkyIntlNumberFormatter does not support accounting format

### ISSUE THREAD

**Issue by Blackbaud-TomMaszk** [blackbaud/skyux-i18n#118]
One of the formats commonly used in accounting products, including FENXT, is formatting amounts in accounting format, which is typically a numeric with a currency symbol and optional parenthesis to indicate a negative number.  Although most [browsers support this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#browser_compatibility), the SkyUX number formatter does not.

It is a requirement of the new AR for financials project to support accounting formatted amounts.

this issue is related to [skyux-core > SkyNumericPipe: expose INTL API Options](https://github.com/blackbaud/skyux-core/issues/179)

### Expected behavior
Should be able format a number using accounting format, which includes parenthesis to indicate a negative number.

Examples:
| Standard format |Accounting format |
| -------: | --------: |
| $100.00  | $100.00 |
| -$50.00 | ($50.00) |

Proposed usage:
```
SkyIntlNumberFormatter.format(
      -100.12,
      'en-US',
      SkyIntlNumberFormatStyle.Currency,
      {
        currency: 'USD',
        currencyAsSymbol: true,
        currencySign: 'accounting'  <-- new option
      }
    );
```
should produce:
```
($100.12)
```

I intend to contribute this new feature.

**Comment by ThomasOrtiz** [comment]
This is fixed by #117 and #123 so we can close this issue.
